/**
 * @file Automatically generated by barrelsby.
 */

export * from "./audio.controller";
export * from "./auth.controller";
export * from "./aws.controller";
export * from "./category.controller";
export * from "./child.controller";
export * from "./dashboard.controller";
export * from "./game.controller";
export * from "./health.controller";
export * from "./lesson.controller";
export * from "./media.controller";
export * from "./notification.controller";
export * from "./progress.controller";
export * from "./user.controller";
